### ISSUE TITLE
Add additional metrics

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/bivac#244]
It would be nice to have some metrics regarding:
- restic backup time
- restic prune time

So that we can see the evolution in time.

**Comment by felixkrohn** [comment]
the following restic metrics could be nice to have as well in order to monitor the backups (and be able to create alerts):
- number of volumes managed
- backup job volume (=bytes written by restic)
- backup job duration (=lifetime of bivac agent container) 
- number of total snapshots
- number of deleted snapshots

**Comment by Vampouille** [comment]
>     * number of total snapshots

Fixed by #316
