### ISSUE TITLE
[401] Unauthorized when running bivac commands

### ISSUE THREAD

**Issue by krisvek** [camptocamp/bivac#255]
I realize you just had a major version bump and rewrite, and documentation is catching up, but was wondering if I could get some help with this:

I've run `bivac manager -o docker --providers.config "providers.config"`
`INFO[0000] Listening on 0.0.0.0:8182`
Verbose (-v) shows it backing up each of my volumes, but I suspect I haven't properly told it WHERE to back those up to...

When I run `bivac info` or 'bivac volumes'
`ERRO[0000] failed to create a new client: failed to connect to the remote Bivac instance: received wrong status code from the Bivac instance: [401] Unauthorized`

I don't think it's a firewall or port thing, what am I missing?
Should I be using the -r to point at a restic repo?

**Comment by cryptobioz** [comment]
The new release is still a _work in progress_ and lacks of documentation.

> Verbose (-v) shows it backing up each of my volumes, but I suspect I haven't properly told it WHERE to back those up to...

You must set a value to `target.url` by using the argument `-r` or the environment variable `BIVAC_TARGET_URL`. This value will then be passed to Restic.
Please note that you also have to set a Restic password, otherwise, the remote backup repository initialization will fail.

> When I run `bivac info` or 'bivac volumes'
> `ERRO[0000] failed to create a new client: failed to connect to the remote Bivac instance: received wrong status code from the Bivac instance: [401] Unauthorized`

When you start the Bivac manager, an HTTP server which exposes API and metrics endpoints is started at the same time. Without authentication process, anyone on the same network as your Bivac manager could make calls to the API and thus perform destructive operations on your backups or retrieve private informations from the backed up volumes. That's the reason why we implemented a pre-shared key authentication system.
To be able to use the Bivac client, you must specify a PSK by using the argument `--server.psk` or the environment variable `BIVAC_SERVER_PSK`.

**Comment by krisvek** [comment]
Excellent, thank you for the information. I haven't had complete success yet, but I am making progress!

Trying a command like this:
`bivac manager -v -o docker -r /path/to/restic/repo --providers.config "providers.config" --server.psk test`

I am now able to run `bivac volumes --server.psk test` and see volume status.
However, all volume backup status is FAILED still.

You mentioned that I would need to set a Restic password or the remote repository init will fail. My Restic repo has a password, I didn't see a way to pass that to bivac in the help menu though.

My other thought is that perhaps bivac doesn't support a local file path for the repo? Or I didn't format the path correctly.

**Comment by cryptobioz** [comment]
You're right, you can't backup your Docker volumes to a local directory. However, I think we could implement this feature quite easily.
To make it quick: I guess you're running Bivac on your system to backup your local Docker volumes. So, Bivac will connect to the Docker socket and start Bivac agent containers which will mount the volumes. Because Restic is run inside the Bivac agent containers, it is unable to access to your local backup directory. 

For now, you must use a remote storage system like S3 or Swift.

**Comment by krisvek** [comment]
Ah, I understand, thanks!
Looks like I can't use it for what I had in mind currently, but it still looks like a promising tool.
I appreciate you taking the time to help!
