### ISSUE TITLE
failed to retrieve the list of namespaces

### ISSUE THREAD

**Issue by codejamninja** [camptocamp/bivac#270]
I get the following error when trying to run on kubernetes.

```
failed to retrieve volumes: failed to retrieve the list of namespaces: namespaces is forbidden: User \"system:serviceaccount:volback:default\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope
```

Can someone show me how to setup on kubernetes?

**Comment by cryptobioz** [comment]
It looks like your error is a permission issue caused by Kubernetes' RBAC.
Did you create a ClusterRole like this one: https://github.com/camptocamp/bivac/blob/master/openshift/bivac-template.yaml#L67-L96?
If you didn't, you can have a look at the [template](https://github.com/camptocamp/bivac/blob/master/openshift/bivac-template.yaml). It was originally built for Openshift but you can extract some parts and build a new "pure" Kubernetes template.

We planned to add template examples and to improve the documentation.

**Comment by codejamninja** [comment]
I was able to figure it out
