### ISSUE TITLE
What is BIVAC_SERVER_PSK

### ISSUE THREAD

**Issue by jackmac92** [camptocamp/bivac#357]
What is the BIVAC_SERVER_PSK for? 

I understand a full explanation may be too time consuming to provide, but if you have a link or suggested searches that would be awesome!

Related to #349

**Comment by cryptobioz** [comment]
You're right, we should spend time to properly write a documentation. Regarding the BIVAC_SERVER_PSK, it is pretty simple. In order to protect the Bivac Server from being accessed by anyone, I chose to setup an authentication method. This method is based on a PSK (pre-shared key), a string like a password.
The variable BIVAC_SERVER_PSK is used to specify the PSK you want to use. If you are on Linux, you can generate one by using the following command:
```bash
$ pwgen -s 30
```

Is that clear for you?

Do you think we Bivac should generate a random PSK if the variable isn't specified?

**Comment by jackmac92** [comment]
@cryptobioz thanks for the explanation, that is clear! 

Re: whether bivac should generate a random PSK if not given, I'm not sure. I think now that there is something you can search the repo for (this issue) it's less of an issue.

Maybe passing `-e BIVAC_SERVER_PSK=generate` (or a separate env var) could be used as an opt-in to auto-generating the PSK? That way at least the dev needs to consider whether they want to supply one or have it generated for them
