### ISSUE TITLE
Improve coverage

### ISSUE THREAD

**Issue by raphink** [camptocamp/bivac#59]
- [ ] Make coverage pass for `handler/handler_test.go` (flags)
- [ ] Add tests (`TestMain`) for `conplicity.go`
- [x] Add tests for `providers/`
- [x] Test bad stdout in `volume/volume_test.go`

**Comment by Pamplemousse** [comment]
Here is what I found while working on #78 .

  * All tests are commented in [`engines/duplicity_test.go`](https://github.com/camptocamp/conplicity/blob/master/engines/duplicity_test.go).
  * [`config/config.go`](https://github.com/camptocamp/conplicity/blob/master/config/config.go) is completely untested.

Note that the first item is not easy to fix as the project seem to have been refactored several times since this has been commented. Most of the mocks have to be corrected.

Second point does not seem really critical, but may be nice to have.

**Comment by raphink** [comment]
Yes, I had to comment out quite a bit when I refractored and did not find the time to redo the tests. Most of the code interacts with Docker which makes it pretty hard to mock.

**Comment by mcanevet** [comment]
Couldn't we use something like https://github.com/orchestrate-io/dvr or https://github.com/dnaeon/go-vcr or https://github.com/ad2games/vcr-go to mock Docker API?

**Comment by mcanevet** [comment]
@raphink I close this issue. We know we have to improve unit tests and probably implement acceptance test. We do not need an issue for that I think.
